package contractbaseline

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/bemulima/agent-orchestrator/internal/agentcontrol"
	"github.com/bemulima/agent-orchestrator/internal/domain"
)

const generatedMarker = "// Generated by Agent Control Plane contract materializer. DO NOT EDIT."

var (
	modulePathPattern        = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._~/-]*$`)
	tsSymbolPattern          = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)
	tsTypeDeclarationPattern = regexp.MustCompile(`(?m)\b(?:export\s+)?(?:interface|type)\s+([A-Za-z_$][A-Za-z0-9_$]*)\b`)
	tsImportPattern          = regexp.MustCompile(`(?m)^\s*import\b(?:[^\n]*?\bfrom\s*)?["']([^"']+)["']`)
	tsSkeletonPattern        = regexp.MustCompile(`(?s)^// Generated by Agent Control Plane contract materializer\. DO NOT EDIT\.\n// Boundary: [a-z0-9-]+\. This declaration intentionally has no behavior\.\nexport interface ([A-Za-z_$][A-Za-z0-9_$]*) \{\}\n?$`)
)

type Materialization struct {
	Contracts []domain.ContractReference
	Files     []domain.ContractBaselineFile
	Paths     []string
}

type Materializer interface {
	Materialize(context.Context, string, string, string, agentcontrol.Profile, []domain.PlannedContractBoundary, []domain.RoutingEvidence) (Materialization, error)
	Validate(context.Context, string, agentcontrol.Profile, []domain.ContractBaselineFile, []domain.ContractReference) domain.ContractBaselineValidation
}

type FileMaterializer struct{}

// PlannedContractReferences derives the bounded path and symbol scope without
// writing files. It is used while a freeze is blocked so shards still retain a
// contract-baseline dependency instead of silently falling back to source HEAD.
func PlannedContractReferences(projectID string, profile agentcontrol.Profile, boundaries []domain.PlannedContractBoundary, evidence []domain.RoutingEvidence) ([]domain.ContractReference, error) {
	evidenceByID := make(map[string]domain.RoutingEvidence, len(evidence))
	for _, item := range evidence {
		evidenceByID[item.ID] = item
	}
	var result []domain.ContractReference
	for _, boundary := range boundaries {
		if boundary.Owner.ProjectID != projectID {
			return nil, fmt.Errorf("contract %q is owned by another repository: %w", boundary.Kind, domain.ErrInvalidStatus)
		}
		symbol, err := contractSymbol(boundary.Kind, profile.ContractLocation.Language)
		if err != nil {
			return nil, err
		}
		surface, hasSurface := agentcontrol.ContractSurfaceForRoute(profile, boundary.Owner.RouteID)
		if !boundary.Existing && !hasSurface && profile.ContractLocation.Language == "go" {
			return nil, fmt.Errorf("Go contract owner route %q has no profile-defined contract surface: %w", boundary.Owner.RouteID, domain.ErrValidation)
		}
		relative := ""
		if profile.ContractLocation.Language == "go" {
			relative = path.Join(surface.Directory, contractFileName(boundary.Kind)+profile.ContractLocation.Extension)
		} else {
			relative = path.Join(profile.ContractLocation.Directory, contractFileName(boundary.Kind)+profile.ContractLocation.Extension)
		}
		if boundary.Existing {
			item, ok := evidenceByID[boundary.SourceEvidenceID]
			if !ok || item.ProjectID != projectID || (item.Kind != "source" && item.Kind != "contract") {
				return nil, fmt.Errorf("existing contract %q lacks same-repository evidence: %w", boundary.Kind, domain.ErrValidation)
			}
			relative = item.Path
			if item.Symbol != "" {
				symbol = item.Symbol
			}
			if !agentcontrol.ContractPathOwnedByRoute(profile, boundary.Owner.RouteID, relative) {
				return nil, fmt.Errorf("existing contract %q is outside its declared owner surface: %w", boundary.Kind, domain.ErrConflict)
			}
		}
		if boundary.TargetPath != "" && boundary.TargetPath != relative {
			return nil, fmt.Errorf("contract %q target path %q differs from approved path %q: %w", boundary.Kind, relative, boundary.TargetPath, domain.ErrConflict)
		}
		if err := agentcontrol.ValidateRelativePath(relative); err != nil {
			return nil, fmt.Errorf("planned contract path is unsafe: %w", err)
		}
		result = append(result, domain.ContractReference{
			Kind: boundary.Kind, RepositoryProjectID: projectID, Path: relative,
			Symbol: symbol, RouteID: boundary.Owner.RouteID, Relation: "implements",
		})
	}
	sort.Slice(result, func(i, j int) bool { return result[i].Kind < result[j].Kind })
	return result, nil
}

func (FileMaterializer) Materialize(
	ctx context.Context,
	root, projectID, repository string,
	profile agentcontrol.Profile,
	boundaries []domain.PlannedContractBoundary,
	evidence []domain.RoutingEvidence,
) (Materialization, error) {
	if err := ctx.Err(); err != nil {
		return Materialization{}, err
	}
	root, err := filepath.Abs(root)
	if err != nil {
		return Materialization{}, fmt.Errorf("resolve repository root: %w", err)
	}
	if profile.ContractLocation.Language == "typescript" && profile.ContractLocation.Directory == "" {
		return Materialization{}, fmt.Errorf("profile %q has no contract location: %w", profile.ID, domain.ErrValidation)
	}
	if profile.ContractLocation.Language == "go" {
		if _, err := readGoModule(root); err != nil {
			return Materialization{}, err
		}
	}
	evidenceByID := make(map[string]domain.RoutingEvidence, len(evidence))
	for _, item := range evidence {
		evidenceByID[item.ID] = item
	}
	result := Materialization{}
	for _, boundary := range boundaries {
		if boundary.Owner.ProjectID != projectID {
			return Materialization{}, fmt.Errorf("contract %q is owned by another repository: %w", boundary.Kind, domain.ErrInvalidStatus)
		}
		symbol, err := contractSymbol(boundary.Kind, profile.ContractLocation.Language)
		if err != nil {
			return Materialization{}, err
		}
		var relative string
		var content []byte
		packageName := ""
		generated := !boundary.Existing
		if boundary.Existing {
			item, ok := evidenceByID[boundary.SourceEvidenceID]
			if !ok || item.ProjectID != projectID || (item.Kind != "source" && item.Kind != "contract") {
				return Materialization{}, fmt.Errorf("existing contract %q lacks same-repository evidence: %w", boundary.Kind, domain.ErrValidation)
			}
			relative = item.Path
			if err := agentcontrol.ValidateRelativePath(relative); err != nil {
				return Materialization{}, fmt.Errorf("existing contract path: %w", err)
			}
			content, err = readContainedFile(root, relative)
			if err != nil {
				return Materialization{}, fmt.Errorf("read existing contract %q: %w", boundary.Kind, err)
			}
			if item.Symbol != "" {
				symbol = item.Symbol
			}
			if profile.ContractLocation.Language == "go" && !agentcontrol.ContractPathOwnedByRoute(profile, boundary.Owner.RouteID, relative) {
				return Materialization{}, fmt.Errorf("existing contract %q is outside its declared owner surface: %w", boundary.Kind, domain.ErrConflict)
			}
			if boundary.TargetPath != "" && boundary.TargetPath != relative {
				return Materialization{}, fmt.Errorf("existing contract %q differs from approved owner target path: %w", boundary.Kind, domain.ErrConflict)
			}
			if profile.ContractLocation.Language == "go" {
				parsed, parseErr := parseGoArtifact(relative, content)
				if parseErr != nil {
					return Materialization{}, fmt.Errorf("parse existing contract %q: %w", boundary.Kind, parseErr)
				}
				packageName = parsed.Name.Name
			}
			if err := validateExistingArtifact(ctx, root, profile, boundary.Owner.RouteID, relative, symbol, packageName, content); err != nil {
				return Materialization{}, fmt.Errorf("validate existing contract %q: %w", boundary.Kind, err)
			}
		} else {
			fileName := contractFileName(boundary.Kind) + profile.ContractLocation.Extension
			if profile.ContractLocation.Language == "go" {
				surface, ok := agentcontrol.ContractSurfaceForRoute(profile, boundary.Owner.RouteID)
				if !ok {
					return Materialization{}, fmt.Errorf("Go contract owner route %q has no profile-defined contract surface: %w", boundary.Owner.RouteID, domain.ErrValidation)
				}
				relative, packageName = path.Join(surface.Directory, fileName), surface.PackageName
			} else {
				relative = path.Join(profile.ContractLocation.Directory, fileName)
			}
			if boundary.TargetPath != "" && boundary.TargetPath != relative {
				return Materialization{}, fmt.Errorf("contract %q differs from approved owner target path: %w", boundary.Kind, domain.ErrConflict)
			}
			if err := agentcontrol.ValidateRelativePath(relative); err != nil {
				return Materialization{}, fmt.Errorf("generated contract path: %w", err)
			}
			content = renderSkeleton(profile, boundary.Kind, symbol, packageName)
			if err := validateGeneratedArtifact(ctx, root, profile, boundary.Owner.RouteID, relative, symbol, packageName, content); err != nil {
				return Materialization{}, fmt.Errorf("validate generated contract %q: %w", boundary.Kind, err)
			}
			filePath, err := safeJoin(root, relative)
			if err != nil {
				return Materialization{}, err
			}
			if info, statErr := os.Lstat(filePath); statErr == nil && (info.Mode()&fs.ModeSymlink != 0 || !info.Mode().IsRegular()) {
				return Materialization{}, fmt.Errorf("generated contract path %q is not a regular file: %w", relative, domain.ErrConflict)
			}
			if existing, readErr := os.ReadFile(filePath); readErr == nil {
				if !strings.Contains(string(existing), generatedMarker) || string(existing) != string(content) {
					return Materialization{}, fmt.Errorf("generated contract path %q collides with a protected file: %w", relative, domain.ErrConflict)
				}
				content = existing
			} else if !os.IsNotExist(readErr) {
				return Materialization{}, fmt.Errorf("inspect generated contract path %q: %w", relative, readErr)
			} else {
				if err := ctx.Err(); err != nil {
					return Materialization{}, err
				}
				if err := os.MkdirAll(filepath.Dir(filePath), 0o755); err != nil {
					return Materialization{}, fmt.Errorf("create contract directory: %w", err)
				}
				if err := ensureContained(root, filePath); err != nil {
					return Materialization{}, err
				}
				file, createErr := os.OpenFile(filePath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
				if createErr != nil {
					return Materialization{}, fmt.Errorf("create generated contract %q: %w", relative, createErr)
				}
				if _, writeErr := file.Write(content); writeErr != nil {
					_ = file.Close()
					return Materialization{}, fmt.Errorf("write generated contract %q: %w", relative, writeErr)
				}
				if closeErr := file.Close(); closeErr != nil {
					return Materialization{}, fmt.Errorf("close generated contract %q: %w", relative, closeErr)
				}
			}
		}
		filePath, err := safeJoin(root, relative)
		if err != nil {
			return Materialization{}, err
		}
		persisted, err := os.ReadFile(filePath)
		if err != nil {
			return Materialization{}, fmt.Errorf("read persisted contract %q: %w", relative, err)
		}
		if string(persisted) != string(content) {
			return Materialization{}, fmt.Errorf("persisted contract %q differs from rendered content: %w", relative, domain.ErrConflict)
		}
		result.Files = append(result.Files, domain.ContractBaselineFile{Path: relative, SHA256: contentHash(persisted), Generated: generated})
		result.Paths = append(result.Paths, relative)
		result.Contracts = append(result.Contracts, domain.ContractReference{
			Kind: boundary.Kind, RepositoryProjectID: projectID, Path: relative,
			Symbol: symbol, RouteID: boundary.Owner.RouteID, Relation: "implements",
		})
	}
	sort.Slice(result.Files, func(i, j int) bool { return result.Files[i].Path < result.Files[j].Path })
	sort.Slice(result.Contracts, func(i, j int) bool { return result.Contracts[i].Kind < result.Contracts[j].Kind })
	result.Paths = uniquePaths(result.Paths)
	validation := (FileMaterializer{}).Validate(ctx, root, profile, result.Files, result.Contracts)
	if !validation.Passed {
		return Materialization{}, fmt.Errorf("materialized contracts failed validation: %s: %w", strings.Join(validation.Reasons, "; "), domain.ErrValidation)
	}
	return result, nil
}

func (FileMaterializer) Validate(ctx context.Context, root string, profile agentcontrol.Profile, files []domain.ContractBaselineFile, contracts []domain.ContractReference) domain.ContractBaselineValidation {
	result := domain.ContractBaselineValidation{Passed: true, Reasons: []string{}}
	if profile.ContractLocation.Language == "go" {
		if _, err := readGoModule(root); err != nil {
			result.Passed = false
			result.Reasons = append(result.Reasons, err.Error())
		}
	}
	contractsByPath := make(map[string][]domain.ContractReference)
	for _, contract := range contracts {
		contractsByPath[contract.Path] = append(contractsByPath[contract.Path], contract)
	}
	for _, file := range files {
		if err := ctx.Err(); err != nil {
			result.Passed = false
			result.Reasons = append(result.Reasons, err.Error())
			break
		}
		content, err := readContainedFile(root, file.Path)
		if err != nil {
			result.Passed = false
			result.Reasons = append(result.Reasons, fmt.Sprintf("%s: %v", file.Path, err))
			continue
		}
		if contentHash(content) != file.SHA256 {
			result.Passed = false
			result.Reasons = append(result.Reasons, "source hash changed for "+file.Path)
			continue
		}
		refs := contractsByPath[file.Path]
		if len(refs) == 0 {
			result.Passed = false
			result.Reasons = append(result.Reasons, "contract file has no declared boundary reference: "+file.Path)
			continue
		}
		routeID := refs[0].RouteID
		for _, ref := range refs {
			if ref.RouteID != routeID || !agentcontrol.ContractPathOwnedByRoute(profile, ref.RouteID, file.Path) {
				result.Passed = false
				result.Reasons = append(result.Reasons, "contract file is not in one consistent declared owner surface: "+file.Path)
			}
		}
		packageName := ""
		if profile.ContractLocation.Language == "go" {
			if file.Generated && agentcontrol.ContractPathUnderSurface(profile, routeID, file.Path) {
				surface, _ := agentcontrol.ContractSurfaceForRoute(profile, routeID)
				packageName = surface.PackageName
			} else if parsed, parseErr := parseGoArtifact(file.Path, content); parseErr == nil {
				packageName = parsed.Name.Name
			}
		}
		if err := validateFileByProfile(ctx, root, profile, routeID, file.Path, packageName, content, file.Generated); err != nil {
			result.Passed = false
			result.Reasons = append(result.Reasons, fmt.Sprintf("%s: %v", file.Path, err))
		}
	}
	return result
}

func renderSkeleton(profile agentcontrol.Profile, kind, symbol, packageName string) []byte {
	if profile.ContractLocation.Language == "go" {
		return []byte(fmt.Sprintf("%s\n// Boundary: %s. This declaration intentionally has no behavior.\npackage %s\n\n// %s is a behavior-free boundary placeholder.\ntype %s interface{}\n", generatedMarker, kind, packageName, symbol, symbol))
	}
	return []byte(fmt.Sprintf("%s\n// Boundary: %s. This declaration intentionally has no behavior.\nexport interface %s {}\n", generatedMarker, kind, symbol))
}

func validateGeneratedArtifact(ctx context.Context, root string, profile agentcontrol.Profile, routeID, relative, symbol, packageName string, content []byte) error {
	if err := agentcontrol.ValidateRelativePath(relative); err != nil {
		return err
	}
	if strings.Contains(string(content), "import ") || strings.Contains(string(content), "require(") {
		return fmt.Errorf("generated contracts must not introduce imports")
	}
	if profile.ContractLocation.Language == "go" && (!token.IsIdentifier(symbol) || token.Lookup(symbol).IsKeyword()) {
		return fmt.Errorf("invalid Go contract symbol %q", symbol)
	}
	if profile.ContractLocation.Language == "typescript" && !tsSymbolPattern.MatchString(symbol) {
		return fmt.Errorf("invalid TypeScript contract symbol %q", symbol)
	}
	if profile.ContractLocation.Language == "go" {
		parsed, err := parseGoArtifact(relative, content)
		if err != nil || !isBehaviorFreeGoSkeleton(parsed) {
			return fmt.Errorf("generated Go contract is not a behavior-free placeholder")
		}
	} else if profile.ContractLocation.Language == "typescript" && !tsSkeletonPattern.Match(content) {
		return fmt.Errorf("generated TypeScript contract is not a behavior-free placeholder")
	}
	return validateFileByProfile(ctx, root, profile, routeID, relative, packageName, content, true)
}

func validateExistingArtifact(ctx context.Context, root string, profile agentcontrol.Profile, routeID, relative, symbol, packageName string, content []byte) error {
	if err := agentcontrol.ValidateRelativePath(relative); err != nil {
		return err
	}
	if profile.ContractLocation.Language == "go" {
		if path.Ext(relative) != profile.ContractLocation.Extension {
			return fmt.Errorf("existing contract extension does not match profile")
		}
		if !token.IsIdentifier(symbol) || token.Lookup(symbol).IsKeyword() {
			return fmt.Errorf("invalid Go contract symbol %q", symbol)
		}
		parsed, err := parseGoArtifact(relative, content)
		if err != nil {
			return err
		}
		if parsed.Name.Name != packageName {
			return fmt.Errorf("existing contract package does not match its source package")
		}
		if err := goImportsAllowed(ctx, root, profile, routeID, parsed); err != nil {
			return err
		}
		if symbol != "" && !declaresGoSymbol(parsed, symbol) {
			return fmt.Errorf("existing contract does not declare symbol %q", symbol)
		}
		return nil
	}
	if profile.ContractLocation.Language == "typescript" {
		if path.Ext(relative) != profile.ContractLocation.Extension {
			return fmt.Errorf("existing contract extension does not match profile")
		}
		if !tsSymbolPattern.MatchString(symbol) {
			return fmt.Errorf("invalid TypeScript contract symbol %q", symbol)
		}
		if err := validateFileByProfile(ctx, root, profile, routeID, relative, "", content, false); err != nil {
			return err
		}
		for _, match := range tsTypeDeclarationPattern.FindAllStringSubmatch(string(content), -1) {
			if len(match) == 2 && match[1] == symbol {
				return nil
			}
		}
		return fmt.Errorf("existing contract does not declare type symbol %q", symbol)
	}
	return fmt.Errorf("unsupported contract language %q", profile.ContractLocation.Language)
}

func validateFileByProfile(ctx context.Context, root string, profile agentcontrol.Profile, routeID, relative, packageName string, content []byte, generated bool) error {
	if path.Ext(relative) != profile.ContractLocation.Extension {
		return fmt.Errorf("contract extension does not match profile")
	}
	if profile.ContractLocation.Language == "go" {
		parsed, err := parseGoArtifact(relative, content)
		if err != nil {
			return err
		}
		if packageName == "" || parsed.Name.Name != packageName {
			return fmt.Errorf("package %q does not match owner package %q", parsed.Name.Name, packageName)
		}
		if err := goImportsAllowed(ctx, root, profile, routeID, parsed); err != nil {
			return err
		}
		if generated {
			if err := validateGeneratedGoDeclarations(parsed, profile, routeID); err != nil {
				return err
			}
		}
		return nil
	}
	if profile.ContractLocation.Language == "typescript" {
		text := string(content)
		if strings.Contains(text, "require(") {
			return fmt.Errorf("contract uses require, which is not allowed")
		}
		for _, match := range tsImportPattern.FindAllStringSubmatch(text, -1) {
			if len(match) != 2 || !profileImportAllowed(profile, match[1]) {
				return fmt.Errorf("contract imports are not allowed by profile")
			}
		}
		if strings.Contains(text, "function ") || strings.Contains(text, "=>") || strings.Contains(text, "class ") {
			return fmt.Errorf("contract skeleton contains behavior")
		}
		if generated && (!hasOnlyTypeScriptDeclarations(text) || tsImplementationPattern.MatchString(text)) {
			return fmt.Errorf("TypeScript contract contains implementation behavior")
		}
		return nil
	}
	return fmt.Errorf("unsupported contract language %q", profile.ContractLocation.Language)
}

func validateGeneratedGoDeclarations(file *ast.File, profile agentcontrol.Profile, routeID string) error {
	for _, declaration := range file.Decls {
		switch node := declaration.(type) {
		case *ast.FuncDecl:
			return fmt.Errorf("contract contains a top-level function declaration")
		case *ast.GenDecl:
			switch node.Tok {
			case token.IMPORT, token.TYPE:
				continue
			case token.VAR:
				for _, raw := range node.Specs {
					value, ok := raw.(*ast.ValueSpec)
					if !ok || len(value.Names) != 1 {
						return fmt.Errorf("contract contains an unsupported variable declaration")
					}
					name := value.Names[0].Name
					if !contractValueAllowed(profile, routeID, name) || !isErrorSentinel(file, name) {
						return fmt.Errorf("contract contains an unapproved variable declaration %q", name)
					}
				}
			default:
				return fmt.Errorf("contract contains an unsupported %s declaration", node.Tok)
			}
		default:
			return fmt.Errorf("contract contains an unsupported top-level declaration")
		}
	}
	return nil
}

func parseGoArtifact(filename string, content []byte) (*ast.File, error) {
	parsed, err := parser.ParseFile(token.NewFileSet(), filename, content, parser.AllErrors)
	if err != nil {
		return nil, fmt.Errorf("invalid Go syntax: %w", err)
	}
	return parsed, nil
}

func profileImportAllowed(profile agentcontrol.Profile, importPath string) bool {
	for _, prefix := range profile.ContractLocation.AllowImports {
		if importPath == prefix || strings.HasPrefix(importPath, strings.TrimSuffix(prefix, "/")+"/") {
			return true
		}
	}
	return false
}

func isBehaviorFreeGoSkeleton(parsed *ast.File) bool {
	if len(parsed.Imports) != 0 || len(parsed.Decls) != 1 {
		return false
	}
	declaration, ok := parsed.Decls[0].(*ast.GenDecl)
	if !ok || declaration.Tok != token.TYPE || len(declaration.Specs) != 1 {
		return false
	}
	spec, ok := declaration.Specs[0].(*ast.TypeSpec)
	if !ok {
		return false
	}
	contract, ok := spec.Type.(*ast.InterfaceType)
	return ok && contract.Methods != nil && len(contract.Methods.List) == 0
}

func declaresGoSymbol(parsed *ast.File, symbol string) bool {
	for _, declaration := range parsed.Decls {
		switch value := declaration.(type) {
		case *ast.FuncDecl:
			if value.Name.Name == symbol {
				return true
			}
		case *ast.GenDecl:
			for _, spec := range value.Specs {
				switch item := spec.(type) {
				case *ast.TypeSpec:
					if item.Name.Name == symbol {
						return true
					}
				case *ast.ValueSpec:
					for _, name := range item.Names {
						if name.Name == symbol {
							return true
						}
					}
				}
			}
		}
	}
	return false
}

func readGoModule(root string) (string, error) {
	content, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return "", fmt.Errorf("read Go module metadata: %w", err)
	}
	for _, line := range strings.Split(string(content), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 2 && fields[0] == "module" {
			module := strings.Trim(fields[1], "\"")
			if !modulePathPattern.MatchString(module) || strings.Contains(module, "//") || strings.Contains(module, "..") {
				return "", fmt.Errorf("invalid Go module path in go.mod: %w", domain.ErrValidation)
			}
			for _, segment := range strings.Split(module, "/") {
				if segment == "" || segment == "." || segment == ".." {
					return "", fmt.Errorf("invalid Go module path in go.mod: %w", domain.ErrValidation)
				}
			}
			return module, nil
		}
	}
	return "", fmt.Errorf("go.mod has no module declaration: %w", domain.ErrValidation)
}

func contractSymbol(kind, language string) (string, error) {
	parts := strings.FieldsFunc(kind, func(value rune) bool {
		return !(value >= 'a' && value <= 'z' || value >= 'A' && value <= 'Z' || value >= '0' && value <= '9')
	})
	var builder strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		builder.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	symbol := builder.String()
	if language == "go" && (!token.IsIdentifier(symbol) || token.Lookup(symbol).IsKeyword()) ||
		language == "typescript" && !tsSymbolPattern.MatchString(symbol) {
		return "", fmt.Errorf("contract kind %q cannot produce a valid symbol: %w", kind, domain.ErrValidation)
	}
	return symbol, nil
}

func contractFileName(kind string) string {
	var builder strings.Builder
	for index, char := range kind {
		if char >= 'A' && char <= 'Z' {
			char += 'a' - 'A'
		}
		if char >= 'a' && char <= 'z' || char >= '0' && char <= '9' {
			builder.WriteRune(char)
		} else if builder.Len() > 0 && !strings.HasSuffix(builder.String(), "_") && index+1 < len(kind) {
			builder.WriteByte('_')
		}
	}
	return strings.Trim(builder.String(), "_")
}

func safeJoin(root, relative string) (string, error) {
	if err := agentcontrol.ValidateRelativePath(relative); err != nil {
		return "", fmt.Errorf("unsafe materialized path: %w", err)
	}
	filePath := filepath.Join(root, filepath.FromSlash(relative))
	if err := ensureContained(root, filePath); err != nil {
		return "", err
	}
	return filePath, nil
}

func ensureContained(root, target string) error {
	rootResolved, err := filepath.EvalSymlinks(root)
	if err != nil {
		return fmt.Errorf("resolve repository root: %w", err)
	}
	rootResolved, err = filepath.Abs(rootResolved)
	if err != nil {
		return fmt.Errorf("resolve repository root: %w", err)
	}
	probe := target
	for {
		resolved, resolveErr := filepath.EvalSymlinks(probe)
		if resolveErr == nil {
			relative, relErr := filepath.Rel(rootResolved, resolved)
			if relErr != nil || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) || filepath.IsAbs(relative) {
				return fmt.Errorf("materialized path escapes repository through symlink: %w", domain.ErrValidation)
			}
			return nil
		}
		if !os.IsNotExist(resolveErr) {
			return fmt.Errorf("resolve materialized path: %w", resolveErr)
		}
		parent := filepath.Dir(probe)
		if parent == probe {
			return fmt.Errorf("materialized path has no contained parent: %w", domain.ErrValidation)
		}
		probe = parent
	}
}

func readContainedFile(root, relative string) ([]byte, error) {
	filePath, err := safeJoin(root, relative)
	if err != nil {
		return nil, err
	}
	info, err := os.Lstat(filePath)
	if err != nil {
		return nil, err
	}
	if !info.Mode().IsRegular() || info.Mode()&fs.ModeSymlink != 0 {
		return nil, fmt.Errorf("contract source is not a regular repository file")
	}
	return os.ReadFile(filePath)
}

func contentHash(content []byte) string {
	hash := sha256.Sum256(content)
	return hex.EncodeToString(hash[:])
}

func uniquePaths(values []string) []string {
	seen := map[string]struct{}{}
	result := make([]string, 0, len(values))
	for _, value := range values {
		if _, ok := seen[value]; !ok {
			seen[value] = struct{}{}
			result = append(result, value)
		}
	}
	sort.Strings(result)
	return result
}
