ALTER TABLE plan DROP CONSTRAINT plan_status_check;
ALTER TABLE plan ADD CONSTRAINT plan_status_check CHECK (status IN (
    'draft', 'discussion', 'ready_for_approval', 'planned',
    'awaiting_approval', 'approved', 'running', 'paused',
    'completed', 'failed', 'cancelled'
));

ALTER TABLE plan
    ADD COLUMN source_kind varchar(32) NOT NULL DEFAULT 'discussion'
        CHECK (source_kind IN ('discussion', 'issue')),
    ADD COLUMN discussion_revision integer NOT NULL DEFAULT 1
        CHECK (discussion_revision > 0),
    ADD COLUMN approved_fingerprint varchar(64);

CREATE TABLE plan_comment (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    plan_id uuid NOT NULL REFERENCES plan(id) ON DELETE CASCADE,
    revision integer NOT NULL CHECK (revision > 0),
    author varchar(255) NOT NULL,
    body text NOT NULL CHECK (length(btrim(body)) BETWEEN 1 AND 10000),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX plan_comment_plan_revision_idx
    ON plan_comment (plan_id, revision, created_at, id);

CREATE TABLE work_item (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    plan_id uuid NOT NULL REFERENCES plan(id) ON DELETE CASCADE,
    task_id uuid REFERENCES task(id) ON DELETE CASCADE,
    project_id uuid NOT NULL REFERENCES project(id) ON DELETE RESTRICT,
    kind varchar(32) NOT NULL CHECK (kind IN ('issue', 'pull_request')),
    provider varchar(32) NOT NULL CHECK (provider IN ('github', 'gitlab')),
    issue_type varchar(32) CHECK (issue_type IS NULL OR issue_type IN (
        'question', 'idea', 'task', 'bug', 'research'
    )),
    status varchar(32) NOT NULL CHECK (status IN (
        'proposed', 'published', 'closed', 'cancelled'
    )),
    title varchar(255) NOT NULL,
    body text NOT NULL,
    labels jsonb NOT NULL CHECK (jsonb_typeof(labels) = 'array'),
    milestone varchar(255) NOT NULL,
    assignees jsonb NOT NULL CHECK (jsonb_typeof(assignees) = 'array'),
    reviewers jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(reviewers) = 'array'),
    source_branch varchar(255) NOT NULL DEFAULT '',
    target_branch varchar(255) NOT NULL DEFAULT '',
    external_number bigint,
    external_url text NOT NULL DEFAULT '',
    agent_role varchar(64) NOT NULL CHECK (agent_role IN (
        'issue-manager', 'pull-request-manager'
    )),
    agent_thread_id varchar(255) NOT NULL,
    complexity varchar(32) NOT NULL CHECK (complexity IN (
        'low', 'medium', 'high', 'critical'
    )),
    model_profile varchar(32) NOT NULL CHECK (model_profile IN (
        'fast', 'standard', 'deep', 'review'
    )),
    plan_fingerprint varchar(64) NOT NULL,
    idempotency_key varchar(255) NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    published_at timestamptz,
    CHECK ((kind = 'issue' AND issue_type IS NOT NULL) OR
           (kind = 'pull_request' AND issue_type IS NULL)),
    CHECK ((status = 'proposed' AND external_number IS NULL AND external_url = '') OR
           (status <> 'proposed' AND external_number IS NOT NULL AND external_number > 0 AND external_url <> ''))
);

CREATE UNIQUE INDEX work_item_task_issue_unique
    ON work_item (task_id) WHERE kind = 'issue' AND status <> 'cancelled';
CREATE UNIQUE INDEX work_item_task_pull_request_unique
    ON work_item (task_id) WHERE kind = 'pull_request' AND status <> 'cancelled';
CREATE UNIQUE INDEX work_item_external_unique
    ON work_item (provider, project_id, external_number)
    WHERE external_number IS NOT NULL;
CREATE INDEX work_item_plan_status_idx ON work_item (plan_id, status, kind);

COMMENT ON TABLE work_item IS
    'Owner-reviewed issue/PR proposals generated by dedicated manager agents.';
