"use client";

import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArchitectureGraph } from "@/components/architecture-graph";
import { Failure, Loading } from "@/components/page-state";
import { apiGet, formatDate, shortID } from "@/lib/api";
import { architectureCurrentSchema } from "@/lib/schemas";

export default function ArchitecturePage() {
  const query = useQuery({ queryKey: ["architecture", "current"], queryFn: () => apiGet("/api/v1/architecture/current", architectureCurrentSchema) });
  const [selected, setSelected] = useState(""); const [search, setSearch] = useState(""); const [kind, setKind] = useState("");
  const model = useMemo(() => { const current = query.data; if (!current) return current; const services = current.services.filter(service => (!search || `${service.name} ${service.purpose}`.toLowerCase().includes(search.toLowerCase())) && (!kind || service.service_kind === kind)); const ids = new Set(services.map(service => service.project_id)); return { ...current, services, relations: current.relations.filter(relation => ids.has(relation.source_project_id) && ids.has(relation.target_project_id)) }; }, [query.data, search, kind]);
  if (query.isLoading) return <Loading />; if (query.error) return <Failure error={query.error} />; const current = query.data!; const service = current.services.find(item => item.project_id === selected);
  return <div className="page architecture-page"><header><div><p className="eyebrow">Architecture Control Center</p><h1>Текущая архитектура</h1><p>Только подтверждённая CURRENT-проекция topology. Визуальное перетаскивание не меняет архитектурные данные.</p></div></header>
    <section className="panel"><div className="architecture-meta"><strong>Режим: {current.mode}</strong><span>Topology {shortID(current.topology_revision_id || "empty")}</span><span>Сформировано {formatDate(current.generated_at)}</span>{current.topology_stale && <strong className="warning">Topology может отставать от последнего discovery snapshot</strong>}</div><div className="architecture-filters"><input aria-label="Поиск сервиса" placeholder="Поиск сервиса или purpose" value={search} onChange={event => setSearch(event.target.value)} /><select aria-label="Фильтр по виду" value={kind} onChange={event => setKind(event.target.value)}><option value="">Все виды</option>{Array.from(new Set(current.services.map(item => item.service_kind))).sort().map(value => <option key={value}>{value}</option>)}</select><button onClick={() => { setSearch(""); setKind(""); setSelected(""); }}>Сбросить</button></div></section>
    {!model?.services.length ? <section className="panel"><h2>Topology пока пуста</h2><p>Архитектура появится после read-only discovery и topology rebuild.</p></section> : <section className="architecture-workspace"><ArchitectureGraph model={model} onService={setSelected} /><aside className="panel architecture-detail">{service ? <><h2>{service.name}</h2><p>{service.purpose || "Purpose not discovered yet"}</p><p><strong>Stack:</strong> {service.stack.map(item => item.value || item.name).join(", ") || "Unknown"}</p><p><strong>Capabilities:</strong> {service.capabilities.map(item => item.name).join(", ") || "Unknown"}</p><p><strong>Ownership:</strong> {service.ownership.map(item => `${item.resource_type}: ${item.resource_name}`).join(", ") || "Unknown"}</p><p><strong>Contracts:</strong> {service.contract_count}; dependencies: {service.dependency_count}; consumers: {service.consumer_count}</p><p><strong>Drift:</strong> {service.drift_status}</p><h3>Contracts</h3>{current.contracts.filter(item => item.project_id === service.project_id).map(contract => <div key={contract.id}><strong>{contract.type} · {contract.code}</strong><p>{contract.method} {contract.path} {contract.subject} · {contract.direction} · {contract.version || "version unknown"}</p><small>{contract.schema_discovered ? "Schema discovered" : "Schema not discovered yet"}{contract.evidence.source_path ? ` · ${contract.evidence.source_path}` : ""}</small></div>)}</> : <><h2>Выберите сервис</h2><p>Кликните node, чтобы увидеть подтверждённые contracts, relations, evidence и drift.</p></>}</aside></section>}</div>;
}
